version: '{build}'
image: Visual Studio 2015
platform:
- x64
environment:
  global:
    DISTUTILS_USE_SDK: 1
    MSSdk: 1
  matrix:
  - CONDA: 36
  - CONDA: 37 #bug https://github.com/conda/conda/issues/7024
install:
- cmd: '"%VS140COMNTOOLS%\..\..\VC\vcvarsall.bat" %PLATFORM%'
- ps: |
    if ($env:PYTHON) {
      if ($env:PLATFORM -eq "x64") { $env:PYTHON = "$env:PYTHON-x64" }
      $env:PATH = "C:\Python$env:PYTHON\;C:\Python$env:PYTHON\Scripts\;$env:PATH"
      pip install --disable-pip-version-check --user --upgrade pip setuptools
    } elseif ($env:CONDA) {
      if ($env:PLATFORM -eq "x64") { $env:CONDA = "$env:CONDA-x64" }
      $env:PATH = "C:\Miniconda$env:CONDA\;C:\Miniconda$env:CONDA\Scripts\;$env:PATH"
      conda config --set always_yes yes --set changeps1 no
      conda config --add channels conda-forge
      conda update -q conda
      conda install -q conda-build pytest
    }
build_script:
- ps: |
    if ($env:PYTHON) {
      python setup.py sdist
      pip install --verbose dist\fpsim2-0.1.1.tar.gz
    } else {
      conda build conda.recipe
      conda install -c C:\Miniconda$env:CONDA\conda-bld\ fpsim2
    }
test_script:
- ps: pytest
