# name: CI
# on:
#   workflow_dispatch:
#   pull_request:
#     branches:
#       - master
#   push:
#     branches:
#       - '*'
#     tags: '*'
# jobs:
#   test:
#     name: FPSim2 (${{ matrix.os }}, ${{ matrix.python-version }}, ${{ matrix.rdkit-version }})
#     runs-on: ${{ matrix.os }}
#     strategy:
#       fail-fast: false
#       matrix:
#         os: ["ubuntu-latest", "macos-latest", "windows-latest"]
#         python-version: ["3.8", "3.9", "3.10"]
#         rdkit-version: ["2022.09.01"]
#     steps:
#       - uses: actions/checkout@v3
#       - uses: actions/setup-python@v4
#         with:
#           python-version: ${{ matrix.python-version }}
#       - name: Install dependencies and package
#         run: |
#           python -m pip install --upgrade pip
#           pip install pytest rdkit==${{ matrix.rdkit-version }}
#           pip install -e .
#       - name: Test with pytest
#         run: |
#           pytest
