# name: FPSim2 PotgreSQL tests
# on:
#   workflow_dispatch:
#   pull_request:
#     branches:
#       - master
#   push:
#     branches:
#       - '*'
#     tags: '*'

# jobs:
#   # Label of the container job
#   container-job:
#     # Containers must run in Linux based operating systems
#     runs-on: ubuntu-latest
#     # Docker Hub image that `container-job` executes in
#     container: python:3.10-bullseye

#     # Service containers to run with `container-job`
#     services:
#       # Label used to access the service container
#       postgres:
#         # Docker Hub image
#         image: postgres
#         # Provide the password for postgres
#         env:
#           POSTGRES_PASSWORD: postgres
#         # Set health checks to wait until postgres has started
#         options: >-
#           --health-cmd pg_isready
#           --health-interval 10s
#           --health-timeout 5s
#           --health-retries 5

#     steps:
#       # Downloads a copy of the code in your repository before running CI tests
#       - name: Check out repository code
#         uses: actions/checkout@v3

#       # Performs a clean installation of all dependencies in the `package.json` file
#       # For more information, see https://docs.npmjs.com/cli/ci.html
#       - name: Install dependencies
#         run: |
#           python -m pip install --upgrade pip
#           pip install pytest psycopg2
#           pip install -e .

#       - name: Run PostgreSQL tests
#         run: |
#           pytest
#         # Environment variables used by the `client.js` script to create a new PostgreSQL table.
#         env:
#           # The hostname used to communicate with the PostgreSQL service container
#           POSTGRES_HOST: postgres
#           # The default PostgreSQL port
#           POSTGRES_PORT: 5432
